# Generated by Django 6.0 on 2025-12-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0002_topic_newspaper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redactor',
            name='years_of_experience',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
