# Generated by Django 6.0 on 2025-12-26 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0004_alter_newspaper_published_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspaper',
            name='topic',
        ),
        migrations.AddField(
            model_name='newspaper',
            name='topics',
            field=models.ManyToManyField(related_name='newspapers', to='newspaper.topic'),
        ),
    ]
